/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsString,
  MaxLength,
  IsOptional,
  IsNumber,
  Min,
  Max,
  IsDate,
  ValidateNested,
} from "class-validator";

import { Type } from "class-transformer";
import { BookingCreateNestedManyWithoutServicesInput } from "./BookingCreateNestedManyWithoutServicesInput";
import { RatingCreateNestedManyWithoutServicesInput } from "./RatingCreateNestedManyWithoutServicesInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";

@InputType()
class ServiceCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  price?: number | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  date?: Date | null;

  @ApiProperty({
    required: false,
    type: () => BookingCreateNestedManyWithoutServicesInput,
  })
  @ValidateNested()
  @Type(() => BookingCreateNestedManyWithoutServicesInput)
  @IsOptional()
  @Field(() => BookingCreateNestedManyWithoutServicesInput, {
    nullable: true,
  })
  bookings?: BookingCreateNestedManyWithoutServicesInput;

  @ApiProperty({
    required: false,
    type: () => RatingCreateNestedManyWithoutServicesInput,
  })
  @ValidateNested()
  @Type(() => RatingCreateNestedManyWithoutServicesInput)
  @IsOptional()
  @Field(() => RatingCreateNestedManyWithoutServicesInput, {
    nullable: true,
  })
  ratings?: RatingCreateNestedManyWithoutServicesInput;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  image?: InputJsonValue;
}

export { ServiceCreateInput as ServiceCreateInput };
